### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by iBicha** [iBicha/roku-youtube#6]
#### Planned for v0.3.0
- [ ] Branding: new name! **Playlet**
- [ ] Branding: logo **Playlet**
- [ ] Fix project setup (linter/formatter)
- [ ] Fix tooling setup (SceneGraph inspector)
- [ ] Integrate [roku-promise](https://github.com/rokucommunity/roku-promise) package
- [ ] Long-running webserver
- [ ] Webserver router middleware
- [ ] Invidious API definition file
  - [ ] Home layout default definition file
  - [ ] Trending
  - [ ] Popular
  - [ ] User feed
  - [ ] User playlists
- [ ] Registry API
- [ ] Side menu with home page and settings
- [ ] Login page on the web app

#### Roadmap
- [ ] Setup unit tests
- [ ] Invidious API definition file
  - [ ] Specific user playlist
  - [ ] Specific channel
- [ ] Web app home layout editor
- [ ] [Spike] Fix non-Latin characters (Unicode on Roku sucks)
- [ ] [Spike] Use component library for automatic updates
  - [ ] [Spike] Configurable installed version (latest vs specific version)
- [ ] Invidious instances API
- [ ] Customize Invidious instance
  - [ ] setting in web app
- [ ] Customize SponsorBlock instance 
  - [ ] setting in web app
- [ ] Search page UI
- [ ] Channel page UI
- [ ] Playlist page UI
- [ ] Closed caption configuration/settings (web app)
- [ ] Live videos / DASH support (/api/manifest/dash/id/${videoId})
- [ ] Comments (web app)
- [ ] Dislike count ([Return YouTube Dislike](https://www.returnyoutubedislike.com/) integration)
- [ ] Launch app to specific video (deep link)
- [ ] Web Share Target API
  - [ ] Video
  - [ ] Channel
  - [ ] Playlist
- [ ] Logs Web API
  - [ ] Logs Web App UI
- [ ] Theme support
  - [ ] Roku
  - [ ] Web App
- [ ] Localization
  - [ ] Roku
  - [ ] Web App

**Comment by samwyse** [comment]
I always reach for the options key to do anything "fancy" but have been slowly training myself to use at the long press instead. Having both ways to open a menu would probably help "old hands" and newbies alive. *Don't* have them do different things!
